devices:
# change this to a keyboard device
- "/dev/input/by-id/usb-BY_Tech_Gaming_Keyboard-event-kbd"
# this is executed when mouseless starts
# startCommand: ""
# the default speed for mouse movement
baseMouseSpeed: 750.0
# the default speed for scrolling
baseScrollSpeed: 20.0
layers:
# the first layer is active at start
- name: initial
  bindings:
    # when tab is held and another key pressed, activate mouse layer
    tab: tap-hold-next tab ; toggle-layer mouse ; 500
    # when a is held for 300ms, activate mouse layer
    c: tap-hold a ; toggle-layer mouse ; 300
    # right alt key toggles arrows layer
    leftalt: toggle-layer arrows
    # switch escape with capslock
    # esc: capslock
    # capslock: esc
# a layer for mouse movement
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true
  bindings:
    # quit mouse layer
    q: layer initial
    # keep the mouse layer active
    space: layer mouse
    r: reload-config
    l: move  1  0
    h: move -1  0
    j: move  0  1
    k: move  0 -1
    n: scroll up
    p: scroll down
    leftalt: speed 4.0
    e: speed 0.3
    capslock: speed 0.1
    a: button left
    t: button middle
    s: button right
    # move to the top left corner
    k0: "exec xdotool mousemove 0 0"
# another layer for arrows and some other keys
- name: arrows
  passThrough: true
  bindings:
    e: up
    s: left
    d: down
    f: right
    q: esc
    w: backspace
    r: delete
    v: enter
